- name: create roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Reccursively remove directory 
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create a app directory 
  ansible.builtin.file:
    path: /app
    state: directory

- name: "download {{component}} application"
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
    dest: /tmp

- name: Unarchive a file that needs to be downloaded 
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes